### ISSUE TITLE
EHF Question concerning negative amounts using prepaid amount element

### ISSUE THREAD

**Issue by linusbohwalli** [anskaffelser/ehf-postaward-g2#105]
Hi Difi,

We've received a file which had a LegalMonetaryTotal and TaxTotal structure like below exemplified. The issue we had was that the PrepaidAmount contained a negative amount. As far as we can find in the specification only RoundingAmount could contain a negative amount (not taking into account the quantity elements). 
However I could not find any information regarding PrepaidAmount being negative.

In our case, the negative PrepaidAmount was actually a fee to be paid (a fee from the previous invoice which was not paid), the calculation in schematron will give correct result since PrepaidAmount is always deducted from the amount to be paid (PayableAmount). 
However, we would interpret PrepaidAmount to only be used when you have an actual PrepaidAmount to present i.e an amount that should be deducted from the payment and not added. An additional fee from a previous invoice might better be presented as an own article (InvoiceLine) Alternatively using the AllowanceCharge structure.

What is your input in this case? Will the EHF format allow the use of negative prepaid amounts?

Please see below example to further explain:

`````` <cac:TaxTotal>
    <cbc:TaxAmount currencyID="NOK">25.00</cbc:TaxAmount>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="NOK">100.00</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="NOK">25.00</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID schemeID="UNCL5305">S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:TaxCategory>
    </cac:TaxSubtotal>
  </cac:TaxTotal>

  <cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="NOK">100.00</cbc:LineExtensionAmount>
    <cbc:TaxExclusiveAmount currencyID="NOK">100.00</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="NOK">125.00</cbc:TaxInclusiveAmount>
    <cbc:PrepaidAmount currencyID="NOK">-25.00</cbc:PrepaidAmount>
    <cbc:PayableAmount currencyID="NOK">150.00</cbc:PayableAmount>
  </cac:LegalMonetaryTotal> ```



We would appreciate your feedback. 

Thank you in advance.
``````

**Comment by SiwMeckelborg** [comment]
Hi, as it is today, there are, as you state nothing to prevent PrepaidAmount from being negative. I have read through documentation from BII and PEPPOL as well, and there are no rules or statements that the PrepaidAmount must be positive. To add a validation rule on this, is only possible in a new major release, as this functionality is not backwards compatible. The issue will be discussed in the next governance meeting in EHF, and I'll report back on the result of that discussion.
