### ISSUE TITLE
Lag mer utfyllende beskrivelse i kapittel 6.18 Smartform

### ISSUE THREAD

**Issue by 3150jam** [anskaffelser/ehf-postaward-g2#182]
For eksempel om man har en vaskemaskin i katalogen, og på denne kan man bestille innbæring, avemballering og montering som kostnadsfrie tilleggsprodukter. Hvordan kan dette implementeres gjennom Smartform, og enda viktigere, KAN det implementeres gjennom Smartform i EHF Katalog.
![image](https://cloud.githubusercontent.com/assets/12857150/19858934/a3ec33ea-9f83-11e6-843d-3d5e7d2a682a.png)

**Comment by klakegg** [comment]
Blir ikke inkludert i EHF Katalog 1.0. Bør spilles inn til OpenPEPPOL for 3.x-spesifikasjonene.
