### ISSUE TITLE
Possibility to include time - RequestedDeliveryPeriod

### ISSUE THREAD

**Issue by 3150jam** [anskaffelser/ehf-postaward-g2#240]
To incude more precise indication of time for delivery in the order format (EHF and PEPPOL BIS):
http://docs.oasis-open.org/ubl/os-UBL-2.1/xml/UBL-Order-2.0-Example.xml
 
![image](https://user-images.githubusercontent.com/12857150/31498104-6830b062-af61-11e7-967b-41e14cc9b664.png)

**Comment by klakegg** [comment]
Not to be included in EHF Order 1.0.
