### ISSUE TITLE
Add chapters on code lists and add PEPPOL/BII rules to list of validation rules

### ISSUE THREAD

**Issue by SiwMeckelborg** [anskaffelser/ehf-postaward-g2#247]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
Add chapter in each EHF guide for Code lists used
Add PEPPOL and BII rules to chapters on validation rules

**Comment by klakegg** [comment]
Code lists are provided as part of the syntax binding.
