### ISSUE TITLE
Fix use case 2

### ISSUE THREAD

**Issue by bentab** [anskaffelser/ehf-postaward-g2#249]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
Order Agreement:
Use case 2 is wrong. According to doc it should be: cbc:LineExtensionAmount= cbc:Quantity * cbc:PriceAmount *cbc:BaseQuantity

**Comment by klakegg** [comment]
How about this?
`cbc:LineExtensionAmount = cbc:Quantity * (cbc:PriceAmount / cbc:BaseQuantity)`

**Comment by klakegg** [comment]
No feedback received in more than a year.
