### ISSUE TITLE
Allow for more than one order response line pr order line in EHF Order response

### ISSUE THREAD

**Issue by SiwMeckelborg** [anskaffelser/ehf-postaward-g2#264]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
In EHF Orderresponse, there is a restriction that one order response line can only refer once to a order line. This is a norwegian restriction, and the current PEPPOL BIS 28A, describes how to send more than one order response line pr. order line (chapter 9.2.3 in the BIS). This is a common requirement to enable suppliers to indicate different delivery dates for different quantities. Example, 250 boxes ordered, the order response should indicate 50 boxes delivered at date 1, and 200 at date 2. EHF should be changed to reflect same procedure as the PEPPOL BIS.

**Comment by tronder88** [comment]
This should be part of EHF version 3.0.0, as this is a big issue in several companies. It is a requirement as it will improve predictability in the supply chain
