### ISSUE TITLE
EHF Common rule EHF-COMMON-R014, should be changed for Invoice and CreditNote

### ISSUE THREAD

**Issue by SiwMeckelborg** [anskaffelser/ehf-postaward-g2#273]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
In situations with factoring, the factoring company often is the one issuing and sending the invoice or credit note, and they may not be Norwegian companies. 
In many such cases, the Seller is not connected to an AccessPoint at all, and as the EndpointID is used as a kind of "window envelope", it should be allowed to have an EndpointID that is not a Norwegian organisational number, and the rest of the information about the Seller is directly referring to the Seller/Supplier.

**Comment by klakegg** [comment]
Solved by using PEPPOL BIS Billing 3.0.
