### ISSUE TITLE
Broken links 404 Not Found guides/invoice-and-creditnote/2.0/no/vedlegg/index.adoc

### ISSUE THREAD

**Issue by aff** [anskaffelser/ehf-postaward-g2#276]
Please make sure this box is checked before submitting your issue - thank you!

- [ X] Issue is related to guides or validation part of EHF in post-award.

Your issue here:

The links in guides/invoice-and-creditnote/2.0/no/vedlegg/index.adoc to "energiveileder" and "finansveileder" are broken. 

    Veileder for energibransjen https://vefa.difi.no/ehf/guide/energiveileder/
    Veileder for finansbransjen https://vefa.difi.no/ehf/guide/finansveileder/

**Comment by klakegg** [comment]
Fixed.
