### ISSUE TITLE
Linker som er brutt 27.06.2019 15:30

### ISSUE THREAD

**Issue by eloekset** [anskaffelser/ehf-postaward-g2#277]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

Kapittel 6.4.2 har to linker som ikke virker:
- [Valideringsregler arvet fra EHF Common](https://vefa.difi.no/ehf/g2/rules/ehf-common/)
- [Norske valideringsregler](https://vefa.difi.no/ehf/g2/rules/t76-nogov/)

![image](https://user-images.githubusercontent.com/791721/60270358-902dbb80-98f0-11e9-9c88-95eb370ecb7a.png)

**Comment by klakegg** [comment]
Which specification is this related to?
