### ISSUE TITLE
One DespatchAdvice for multiple (partial) orders

### ISSUE THREAD

**Issue by tyskjohan** [anskaffelser/ehf-postaward-g2#278]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

We would like to suggest that on the Dispatch Advice (DA [ASN]) message, the order reference at the header level be made non-mandatory, and to introduce an order (header) reference field at the DA line level.

We have multiple use cases where we are sending goods for multiple orders in the same shipment – either because the shipment represents a “back order” delivery that can span outstanding deliveries from several orders, or because the shipment can be a collated shipment to central receiving for orders from several departments.

This has been declined by OpenPEPPOL; however the first item (non-mandatory at header level) comes from EHF as it's not mandatory in OpenPEPPOL. I think the correct reference is EHF-T16-B15402 - Element 'cac:OrderReference' MUST be provided.

**Comment by klakegg** [comment]
The OrderReference at header level is optional for EHF Despatch Advice 1.0. There will be no changes to the syntax binding for 1.0.
