### ISSUE TITLE
negative zero

### ISSUE THREAD

**Issue by user987234** [anskaffelser/ehf-postaward-g2#279]
Please make sure this box is checked before submitting your issue - thank you!

- [X ] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
The validator treats -0 as less than zero, not zero. This is in violation of standard computer arithmetic ( IEEE754 ) and will cause misc rules to fail when they shouldn't.
Since a standard computer program will always treat -0 as zero, I'm not sure how the validator managed to explicitly change this definition.

**Comment by klakegg** [comment]
Unable to reproduce due to lack of information.
